services:
  db:
    container_name: postgres-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: healthy-programmer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpassword
    ports:
      - "5435:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./sql:/sql

volumes:
  postgres: